version: '3.1'

services:
  postgres:
    image: postgres:14
    container_name: tiktok
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: tiktok_dev
    volumes:
      - tiktok-data:/var/lib/postgresql/data

volumes:
  tiktok-data:
